# Generated by Django 6.0.2 on 2026-02-14 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Project Title', max_length=255)),
                ('industry', models.CharField(help_text='e.g. Real Estate, Healthcare', max_length=100)),
                ('service_description', models.TextField(help_text='Description of the service or product')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=10)),
                ('background_type', models.CharField(help_text='e.g. Office, Gym, Studio', max_length=100)),
                ('avatar_outfit', models.CharField(help_text='e.g. Business Suit, Casual, Doctor Coat', max_length=100)),
                ('constructed_prompt', models.TextField(blank=True, help_text='The full prompt sent to HeyGen')),
                ('heygen_video_id', models.CharField(blank=True, help_text='ID returned by HeyGen API', max_length=100, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Final video URL', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
