# Generated by Django 6.0.2 on 2026-02-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='avatar_id',
            field=models.CharField(default='Abigail_expressive_2024112501', help_text='HeyGen Avatar ID', max_length=100),
        ),
    ]
