# Generated by Django 5.2.11 on 2026-02-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videoproject_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
