# Generated by Django 5.2.13 on 2026-04-12 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPromoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(blank=True, help_text='Uploaded product image — used for Gemini multimodal script generation', null=True, upload_to='product_promo/images/%Y/%m/')),
                ('avatar_id', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_name', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_gender', models.CharField(blank=True, default='', max_length=100)),
                ('avatar_preview_url', models.URLField(blank=True, default='', max_length=1000)),
                ('voice_id', models.CharField(blank=True, default='', max_length=255)),
                ('generated_script', models.TextField(blank=True, default='', help_text='Raw script from Gemini — may be edited before finalization')),
                ('finalized_script', models.TextField(blank=True, default='', help_text='User-confirmed script sent to HeyGen')),
                ('heygen_video_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('video_url', models.URLField(blank=True, default='', max_length=1000)),
                ('video_file', models.FileField(blank=True, help_text='Downloaded mp4 file stored locally', null=True, upload_to='product_promo/videos/%Y/%m/')),
                ('video_status_message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('script_generated', 'Script Generated'), ('script_finalized', 'Script Finalized'), ('video_processing', 'Video Processing'), ('video_completed', 'Video Completed'), ('video_failed', 'Video Failed')], db_index=True, default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_promo_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_promo_user_date'), models.Index(fields=['user', 'status'], name='idx_promo_user_status')],
            },
        ),
    ]
