# Generated by Django 5.2.13 on 2026-04-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpromo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productpromoproject',
            name='idx_promo_user_date',
        ),
        migrations.RemoveIndex(
            model_name='productpromoproject',
            name='idx_promo_user_status',
        ),
        migrations.AlterField(
            model_name='productpromoproject',
            name='avatar_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productpromoproject',
            name='finalized_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productpromoproject',
            name='generated_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productpromoproject',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_promo/images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productpromoproject',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='product_promo/videos/%Y/%m/'),
        ),
    ]
