# Generated by Django 5.2.13 on 2026-04-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpromo', '0002_remove_productpromoproject_idx_promo_user_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpromoproject',
            name='background',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
