# Generated by Django 5.2.13 on 2026-04-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpromo', '0003_productpromoproject_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpromoproject',
            name='is_watermarked',
            field=models.BooleanField(default=False),
        ),
    ]
