# Generated by Django 5.2.13 on 2026-04-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpromo', '0004_productpromoproject_is_watermarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpromoproject',
            name='heygen_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
