# Generated by Django 5.2.13 on 2026-04-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpromo', '0006_productpromoproject_style_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpromoproject',
            name='is_counted',
            field=models.BooleanField(default=False),
        ),
    ]
