# Generated by Django 6.0.2 on 2026-02-05 18:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="User's email address - used for login", max_length=255, unique=True)),
                ('username', models.CharField(help_text="User's username - used for login and display", max_length=30, unique=True)),
                ('is_email_verified', models.BooleanField(default=False, help_text='Has the user verified their email address?')),
                ('auth_provider', models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('apple', 'Apple')], default='email', help_text='How did the user sign up?', max_length=20)),
                ('google_id', models.CharField(blank=True, help_text='Google account ID for OAuth', max_length=255, null=True)),
                ('apple_id', models.CharField(blank=True, help_text='Apple account ID for OAuth', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the user account active?')),
                ('is_staff', models.BooleanField(default=False, help_text='Can the user access the admin site?')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='When did the user create their account?')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When was the user last updated?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_code', models.CharField(help_text='6-digit verification code', max_length=6)),
                ('expires_at', models.DateTimeField(help_text='When does this OTP expire?')),
                ('attempts', models.IntegerField(default=0, help_text='Number of failed verification attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Secure token for password reset', unique=True)),
                ('expires_at', models.DateTimeField(help_text='When does this token expire?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
