# Generated by Django 6.0.2 on 2026-02-05 22:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email to be verified', max_length=255, unique=True)),
                ('username', models.CharField(help_text='Requested username', max_length=30)),
                ('password_hash', models.CharField(help_text='Hashed password', max_length=128)),
                ('otp_code', models.CharField(help_text='6-digit verification code', max_length=6)),
                ('expires_at', models.DateTimeField(help_text='When does this registration expire?')),
                ('attempts', models.IntegerField(default=0, help_text='Number of failed verification attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
