# Generated by Django 6.0.2 on 2026-02-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='otp_code',
            field=models.CharField(blank=True, help_text='6-digit verification code', max_length=6, null=True),
        ),
    ]
