# Generated by Django 5.2.11 on 2026-02-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=1, help_text='Remaining video generation credits'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tier',
            field=models.CharField(choices=[('Free', 'Free'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Free', help_text="User's subscription tier", max_length=20),
        ),
    ]
