# Generated by Django 5.2.11 on 2026-02-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_credits_customuser_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tier',
        ),
    ]
