# Generated by Django 5.2.12 on 2026-03-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_credits_remove_customuser_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Granular access rights for standard staff members'),
        ),
    ]
