from rest_framework import generics, status, permissions
from rest_framework.response import Response
from rest_framework.views import APIView
from django.utils import timezone
from datetime import timedelta
from django.db import models
from django.db.models import Count, Sum
from django.contrib.auth import get_user_model
from rest_framework import filters
from core.throttles import AdminActionThrottle

CustomUser = get_user_model()
from subscriptions.models import UserSubscription, SubscriptionPlan
from videogen.models import VideoProject
from .serializers import AdminUserSerializer, AdminVideoProjectSerializer

# =============================================================================
# PERMISSION CLASSES
# =============================================================================

class IsAdminUser(permissions.BasePermission):
    """
    Allow access only to staff members.
    """
    def has_permission(self, request, view):
        return bool(request.user and request.user.is_authenticated and request.user.is_staff)


class IsSuperUser(permissions.BasePermission):
    """
    Allow access only to superusers.
    """
    def has_permission(self, request, view):
        return bool(request.user and request.user.is_authenticated and request.user.is_superuser)


# =============================================================================
# DASHBOARD STATS
# =============================================================================

class DashboardStatsView(APIView):
    permission_classes = [IsAdminUser]

    def get(self, request):
        now = timezone.now()
        thirty_days_ago = now - timedelta(days=30)
        
        # 1. User Stats (excluding admins and superusers)
        regular_users_qs = CustomUser.objects.filter(is_staff=False, is_superuser=False)
        total_users = regular_users_qs.count()
        new_users_30d = regular_users_qs.filter(date_joined__gte=thirty_days_ago).count()
        
        # 2. Subscription Stats
        active_subscriptions = UserSubscription.objects.filter(status=UserSubscription.Status.ACTIVE).count()
        trial_subscriptions = UserSubscription.objects.filter(status=UserSubscription.Status.TRIAL).count()
        
        # Aggregate Monthly Recurring Revenue (approximate based on active paid plans)
        mrr_data = UserSubscription.objects.filter(
            status=UserSubscription.Status.ACTIVE
        ).aggregate(total_mrr=Sum('plan__price_monthly'))
        approx_mrr = mrr_data['total_mrr'] or 0

        # 3. Video Stats
        total_videos = VideoProject.objects.count()
        completed_videos = VideoProject.objects.filter(status=VideoProject.StatusChoice.VIDEO_COMPLETED).count()
        failed_videos = VideoProject.objects.filter(status=VideoProject.StatusChoice.VIDEO_FAILED).count()
        videos_last_30d = VideoProject.objects.filter(
            status=VideoProject.StatusChoice.VIDEO_COMPLETED,
            updated_at__gte=thirty_days_ago
        ).count()

        # 4. Chart Data: Signups by Day (last 30 days)
        signups_by_day = list(
            CustomUser.objects.filter(date_joined__gte=thirty_days_ago)
            .extra({'date': "date(date_joined)"})
            .values('date')
            .annotate(count=Count('id'))
            .order_by('date')
        )
        
        # 5. Chart Data: Videos Generated by Day (last 30 days)
        videos_by_day = list(
            VideoProject.objects.filter(
                status=VideoProject.StatusChoice.VIDEO_COMPLETED,
                updated_at__gte=thirty_days_ago
            )
            .extra({'date': "date(updated_at)"})
            .values('date')
            .annotate(count=Count('id'))
            .order_by('date')
        )
        
        # Format chart data to ensure all dates are present (simplified for now)
        # In a real production app, you'd fill in the missing days with 0s.
        
        # 6. Chart Data: Subscriptions by Plan (Active/Trial only)
        subscriptions_by_plan = list(
            UserSubscription.objects.filter(
                status__in=[UserSubscription.Status.ACTIVE, UserSubscription.Status.TRIAL]
            )
            .values('plan__name')
            .annotate(count=Count('id'))
            .order_by('-count')
        )
        # Format for Recharts (needs 'name' and 'value')
        formatted_subscriptions_by_plan = [
            {"name": item['plan__name'], "value": item['count']} 
            for item in subscriptions_by_plan
        ]

        return Response({
            "overview": {
                "total_users": total_users,
                "new_users_30d": new_users_30d,
                "active_paid_subscriptions": active_subscriptions,
                "active_trial_subscriptions": trial_subscriptions,
                "approximate_mrr": approx_mrr,
                "total_videos_created": total_videos,
                "completed_videos": completed_videos,
                "completed_videos_30d": videos_last_30d,
                "failed_videos": failed_videos,
            },
            "charts": {
                "signups_by_day": signups_by_day,
                "videos_by_day": videos_by_day,
                "subscriptions_by_plan": formatted_subscriptions_by_plan,
            }
        })


# =============================================================================
# USER MANAGEMENT
# =============================================================================

class AdminChangePasswordView(APIView):
    permission_classes = [IsAdminUser]

    def post(self, request):
        user = request.user
        old_password = request.data.get('old_password')
        new_password = request.data.get('new_password')
        
        if not old_password or not new_password:
            return Response(
                {"error": "Both current and new passwords are required."}, 
                status=status.HTTP_400_BAD_REQUEST
            )
            
        if not user.check_password(old_password):
            return Response(
                {"error": "Incorrect current password."}, 
                status=status.HTTP_400_BAD_REQUEST
            )
            
        user.set_password(new_password)
        user.save(update_fields=['password'])
        
        return Response({"message": "Password updated successfully."}, status=status.HTTP_200_OK)


class AdminUserListView(generics.ListAPIView):
    permission_classes = [IsAdminUser]
    # Only return standard customers
    queryset = CustomUser.objects.filter(is_staff=False, is_superuser=False).order_by('-date_joined')
    serializer_class = AdminUserSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['username', 'email']

class AdminUserDetailView(generics.RetrieveDestroyAPIView):
    permission_classes = [IsAdminUser] # Require admin for GET
    queryset = CustomUser.objects.filter(is_staff=False, is_superuser=False)
    serializer_class = AdminUserSerializer
    
    def delete(self, request, *args, **kwargs):
        # Only superusers can actually delete
        if not request.user.is_superuser:
            return Response({"error": "Only superadmins can delete users."}, status=status.HTTP_403_FORBIDDEN)
        return super().delete(request, *args, **kwargs)


class AdminStaffListView(generics.ListAPIView):
    permission_classes = [IsAdminUser]
    # Return all staff members and superusers
    queryset = CustomUser.objects.filter(models.Q(is_staff=True) | models.Q(is_superuser=True)).order_by('-date_joined')
    serializer_class = AdminUserSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['username', 'email']


class AdminCreateStaffView(APIView):
    # ONLY SUPERUSERS CAN CREATE NEW ADMINS
    permission_classes = [IsSuperUser]
    
    def post(self, request):
        email = request.data.get('email')
        username = request.data.get('username')
        password = request.data.get('password')
        is_superuser = request.data.get('is_superuser', False)
        admin_permissions = request.data.get('admin_permissions', {})
        
        if not email or not username or not password:
            return Response(
                {"error": "Email, username, and password are required."}, 
                status=status.HTTP_400_BAD_REQUEST
            )
            
        if CustomUser.objects.filter(email=email).exists():
            return Response(
                {"error": "A user with this email already exists."}, 
                status=status.HTTP_400_BAD_REQUEST
            )
            
        if CustomUser.objects.filter(username=username).exists():
            return Response(
                {"error": "A user with this username already exists."}, 
                status=status.HTTP_400_BAD_REQUEST
            )
            
        try:
            if is_superuser:
                user = CustomUser.objects.create_superuser(
                    email=email,
                    username=username,
                    password=password
                )
            else:
                user = CustomUser.objects.create_user(
                    email=email,
                    username=username,
                    password=password,
                    is_staff=True,
                    is_email_verified=True,
                    admin_permissions=admin_permissions
                )
            
            return Response({
                "message": f"New Admin {user.email} successfully created.",
                "user": AdminUserSerializer(user).data
            }, status=status.HTTP_201_CREATED)
            
        except ValueError as e:
            return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response(
                {"error": "An error occurred while creating the admin account."}, 
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )

class AdminUpdateStaffPermissionsView(APIView):
    permission_classes = [IsSuperUser]
    throttle_classes = [AdminActionThrottle]
    
    def _update(self, request, pk):
        if not request.user.is_superuser:
            return Response(
                {"error": "Only superadmins can modify staff permissions."}, 
                status=status.HTTP_403_FORBIDDEN
            )
            
        try:
            user_to_update = CustomUser.objects.get(
                pk=pk
            )
            if not user_to_update.is_staff and not user_to_update.is_superuser:
                raise CustomUser.DoesNotExist
        except CustomUser.DoesNotExist:
            return Response({"error": "Admin user not found."}, status=status.HTTP_404_NOT_FOUND)
            
        # Prevent superadmins from accidentally revoking their own superuser status
        if request.user.id == user_to_update.id and 'is_superuser' in request.data and not request.data['is_superuser']:
            return Response({"error": "You cannot revoke your own superadmin status."}, status=status.HTTP_400_BAD_REQUEST)
            
        if 'is_superuser' in request.data:
            user_to_update.is_superuser = request.data['is_superuser']
            
        if 'admin_permissions' in request.data:
             # Merge with existing permissions or replace
             current_perms = user_to_update.admin_permissions or {}
             current_perms.update(request.data['admin_permissions'])
             user_to_update.admin_permissions = current_perms
             
        user_to_update.save(update_fields=['is_superuser', 'admin_permissions'])
        
        return Response({
            "message": "Permissions updated successfully", 
            "user": AdminUserSerializer(user_to_update).data
        }, status=status.HTTP_200_OK)

    def put(self, request, pk):
        return self._update(request, pk)

    def patch(self, request, pk):
        return self._update(request, pk)

class AdminDeleteStaffView(APIView):
    permission_classes = [IsSuperUser]
    
    def delete(self, request, pk):
        try:
            # Match superusers too — they may not have is_staff=True
            user = CustomUser.objects.get(
                pk=pk
            )
            if not user.is_staff and not user.is_superuser:
                raise CustomUser.DoesNotExist
        except CustomUser.DoesNotExist:
            return Response({"error": "Staff member not found."}, status=status.HTTP_404_NOT_FOUND)
            
        # Prevent a superadmin from deleting themselves
        if request.user.id == user.id:
            return Response({"error": "You cannot delete your own account."}, status=status.HTTP_400_BAD_REQUEST)
            
        user.delete()
        return Response({"message": "Staff member successfully deleted."}, status=status.HTTP_204_NO_CONTENT)


# =============================================================================
# VIDEO MANAGEMENT
# =============================================================================

class AdminVideoListView(generics.ListAPIView):
    permission_classes = [IsAdminUser]
    queryset = VideoProject.objects.all().select_related('user').order_by('-created_at')
    serializer_class = AdminVideoProjectSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['title', 'user__email', 'industry']

class AdminVideoDetailView(generics.RetrieveAPIView):
    permission_classes = [IsAdminUser]
    queryset = VideoProject.objects.all().select_related('user')
    serializer_class = AdminVideoProjectSerializer
