# Generated by Django 5.2.11 on 2026-02-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_video_duration_seconds',
        ),
    ]
