# Generated by Django 5.2.11 on 2026-02-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscriptionplan_max_video_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='apple_product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='GBP', max_length=5),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='google_product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_priority_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_watermark',
            field=models.BooleanField(default=False, help_text='If True, videos will have a watermark.'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='platform',
            field=models.CharField(choices=[('apple', 'Apple'), ('google', 'Google'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='purchase_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_videos_used',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime count of successful videos during free trial.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_videos_per_month',
            field=models.PositiveIntegerField(default=5, help_text='Monthly video limit. For free trial this is the LIFETIME total.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('starter', 'Starter'), ('pro', 'Pro')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial', 'Free Trial')], default='trial', max_length=20),
        ),
    ]
