# Generated by Django 5.2.11 on 2026-03-01 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_apple_product_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='apple_product_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='google_product_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_watermark',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_videos_per_month',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial', 'Free Trial')], db_index=True, default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='trial_videos_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['transaction_id'], name='idx_sub_transaction'),
        ),
    ]
