from rest_framework import generics, permissions, status, views
from rest_framework.response import Response
from .models import VideoProject
from .serializers import VideoProjectSerializer
from .tasks import generate_video_task

class VideoProjectListCreateView(generics.ListCreateAPIView):
    """
    GET: List all video projects for the authenticated user.
    POST: Create a new video project and start generation.
    """
    permission_classes = [permissions.IsAuthenticated]
    serializer_class = VideoProjectSerializer

    def get_queryset(self):
        return VideoProject.objects.filter(user=self.request.user).order_by('-created_at')

    def perform_create(self, serializer):
        project = serializer.save(user=self.request.user)
        # Trigger the Celery task
        generate_video_task.delay(project.id)

class VideoProjectDetailView(generics.RetrieveAPIView):
    """
    GET: Retrieve details of a specific video project.
    """
    permission_classes = [permissions.IsAuthenticated]
    serializer_class = VideoProjectSerializer
    lookup_field = 'id'

    def get_queryset(self):
        return VideoProject.objects.filter(user=self.request.user)


import json
import os
from django.conf import settings

class AvatarListView(views.APIView):
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request):
        # Load avatars from the JSON file generated by fetch_all_avatars.py
        json_path = os.path.join(settings.BASE_DIR, 'videos', 'avatars.json')
        
        try:
            with open(json_path, 'r') as f:
                all_avatars = json.load(f)
        except FileNotFoundError:
            # Fallback to empty list or basic if file missing
            return Response({"error": "Avatar list not found. Run fetch_all_avatars.py"}, status=500)

        # 1. Filter by Gender
        gender_param = request.query_params.get('gender')
        if gender_param:
            all_avatars = [a for a in all_avatars if a.get('gender', '').lower() == gender_param.lower()]

        # 2. Filter by Outfit (Business, Casual, etc.)
        outfit_param = request.query_params.get('outfit')
        if outfit_param:
            all_avatars = [a for a in all_avatars if outfit_param.lower() in a.get('outfit', '').lower()]
        
        # 3. Limit results for performance if no filters (optional)
        # return Response(all_avatars[:50]) 
        
        return Response(all_avatars)


from .heygen_service import HeyGenClient

class VideoStatusView(views.APIView):
    """
    GET: Force-check the status of a video project from HeyGen Video Agent API
    Link: https://api.heygen.com/v1/video_status.get
    """
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, id):
        try:
            project = VideoProject.objects.get(id=id, user=request.user)
        except VideoProject.DoesNotExist:
            return Response({"error": "Project not found"}, status=status.HTTP_404_NOT_FOUND)

        if not project.heygen_video_id:
            return Response({"error": "Project has no HeyGen Video ID yet"}, status=status.HTTP_400_BAD_REQUEST)

        # Call HeyGen directly
        client = HeyGenClient()
        try:
            response = client.check_status(project.heygen_video_id)
            data = response.get('data', {})
            
            # Update local DB
            heygen_status = data.get('status')
            video_url = data.get('video_url') or data.get('url')
            
            if heygen_status == 'completed':
                project.status = VideoProject.Status.COMPLETED
                project.video_url = video_url
                project.save()
            elif heygen_status == 'failed':
                project.status = VideoProject.Status.FAILED
                project.save()
                
            return Response({
                "id": project.id,
                "heygen_video_id": project.heygen_video_id,
                "status": project.status, # Our mapped status
                "heygen_status": heygen_status, # Raw status
                "video_url": project.video_url,
                "error": data.get('error')
            })

        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_502_BAD_GATEWAY)
