# Generated by Django 5.2.11 on 2026-02-26 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=200)),
                ('service_description', models.TextField()),
                ('avatar_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('avatar_outfit', models.CharField(help_text="Desired outfit keyword (e.g. 'office', 'casual', 'formal')", max_length=200)),
                ('avatar_id', models.CharField(blank=True, max_length=255)),
                ('avatar_name', models.CharField(blank=True, max_length=255)),
                ('avatar_pose', models.CharField(blank=True, max_length=100)),
                ('avatar_outfit_resolved', models.CharField(blank=True, help_text="Outfit parsed from avatar_id e.g. 'office' from 'Abigail_standing_office_front'", max_length=200)),
                ('avatar_preview_url', models.URLField(blank=True)),
                ('generated_script', models.TextField(blank=True)),
                ('finalized_script', models.TextField(blank=True)),
                ('heygen_video_id', models.CharField(blank=True, max_length=255)),
                ('video_url', models.URLField(blank=True)),
                ('video_status_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('avatar_selected', 'Avatar Selected'), ('script_generated', 'Script Generated'), ('script_finalized', 'Script Finalized'), ('video_processing', 'Video Processing'), ('video_completed', 'Video Completed'), ('video_failed', 'Video Failed')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
