# Generated by Django 5.2.11 on 2026-02-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='voice_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='voice_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='voice_preview_url',
            field=models.URLField(blank=True),
        ),
    ]
