# Generated by Django 5.2.11 on 2026-02-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0002_videoproject_voice_id_videoproject_voice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='background',
            field=models.CharField(blank=True, default='', help_text="Avatar background description (e.g. 'modern office', 'city skyline at sunset')", max_length=500),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='title',
            field=models.CharField(default='', help_text='Project/video title', max_length=255),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='video_file',
            field=models.FileField(blank=True, help_text='Saved video file in storage', null=True, upload_to='videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_outfit',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_outfit_resolved',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='video_url',
            field=models.URLField(blank=True, help_text='Temporary HeyGen URL (used to download the video)'),
        ),
    ]
