# Generated by Django 5.2.11 on 2026-03-01 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0003_videoproject_background_videoproject_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproject',
            name='background',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='heygen_video_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('avatar_selected', 'Avatar Selected'), ('script_generated', 'Script Generated'), ('script_finalized', 'Script Finalized'), ('video_processing', 'Video Processing'), ('video_completed', 'Video Completed'), ('video_failed', 'Video Failed')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='videoproject',
            index=models.Index(fields=['user', '-created_at'], name='idx_project_user_date'),
        ),
        migrations.AddIndex(
            model_name='videoproject',
            index=models.Index(fields=['user', 'status'], name='idx_project_user_status'),
        ),
    ]
