# Generated by Django 5.2.11 on 2026-03-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0004_alter_videoproject_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproject',
            name='voice_id',
        ),
        migrations.RemoveField(
            model_name='videoproject',
            name='voice_name',
        ),
        migrations.RemoveField(
            model_name='videoproject',
            name='voice_preview_url',
        ),
        migrations.AddField(
            model_name='videoproject',
            name='avatar_preview_video_url',
            field=models.URLField(blank=True, help_text='Avatar preview video — user watches this to hear the voice'),
        ),
    ]
