# Generated by Django 5.2.12 on 2026-03-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0005_remove_videoproject_voice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, help_text='Detailed description passed to Video Agent prompt', max_length=500)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='videoproject',
            name='avatar_outfit_resolved',
        ),
        migrations.RemoveField(
            model_name='videoproject',
            name='avatar_pose',
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_gender',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_outfit',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_preview_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_preview_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='finalized_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='generated_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='service_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('script_generated', 'Script Generated'), ('script_finalized', 'Script Finalized'), ('video_processing', 'Video Processing'), ('video_completed', 'Video Completed'), ('video_failed', 'Video Failed')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='video_status_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CachedAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_id', models.CharField(max_length=255, unique=True)),
                ('avatar_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_index=True, max_length=10)),
                ('outfit_category', models.CharField(choices=[('business', 'Business'), ('casual', 'Casual'), ('formal', 'Formal'), ('healthcare', 'Healthcare'), ('outdoor', 'Outdoor')], db_index=True, help_text='Admin can change if auto-detection was wrong', max_length=20)),
                ('pose', models.CharField(blank=True, max_length=100)),
                ('angle', models.CharField(blank=True, max_length=100)),
                ('preview_image_url', models.URLField(blank=True)),
                ('preview_video_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['avatar_name', 'outfit_category'],
                'indexes': [models.Index(fields=['outfit_category', 'is_active'], name='idx_avatar_outfit_active')],
            },
        ),
    ]
