# Generated by Django 5.2.12 on 2026-03-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0006_background_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('language_code', models.CharField(blank=True, default='', max_length=20)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('preview_audio_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['language', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cachedavatar',
            name='default_voice_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
