# Generated by Django 5.2.12 on 2026-03-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0007_cachedvoice_cachedavatar_default_voice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='voice_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
