# Generated by Django 5.2.13 on 2026-04-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0008_videoproject_voice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedavatar',
            name='preview_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='cachedavatar',
            name='preview_video_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='cachedvoice',
            name='preview_audio_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_preview_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_preview_video_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
