# Generated by Django 5.2.13 on 2026-04-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0009_alter_cachedavatar_preview_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='description',
            field=models.CharField(blank=True, help_text='Detailed description passed to Video Agent prompt', max_length=1000),
        ),
        migrations.AlterField(
            model_name='background',
            name='icon',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='background',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='cachedavatar',
            name='angle',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='cachedavatar',
            name='avatar_id',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='cachedavatar',
            name='avatar_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cachedavatar',
            name='default_voice_id',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cachedavatar',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cachedavatar',
            name='outfit_category',
            field=models.CharField(choices=[('business', 'Business'), ('casual', 'Casual'), ('formal', 'Formal'), ('healthcare', 'Healthcare'), ('outdoor', 'Outdoor')], db_index=True, help_text='Admin can change if auto-detection was wrong', max_length=100),
        ),
        migrations.AlterField(
            model_name='cachedavatar',
            name='pose',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='cachedvoice',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cachedvoice',
            name='language',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cachedvoice',
            name='language_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cachedvoice',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cachedvoice',
            name='voice_id',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_gender',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_id',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='avatar_outfit',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='background',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='heygen_video_id',
            field=models.CharField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='voice_id',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
