# Generated by Django 5.2.13 on 2026-04-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0010_alter_background_description_alter_background_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='is_watermarked',
            field=models.BooleanField(default=False, help_text='Has the app logo been added to this video?'),
        ),
    ]
