# Generated by Django 5.2.13 on 2026-04-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0012_fix_video_status_message_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='heygen_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='heygen_video_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
