# Generated by Django 5.2.13 on 2026-04-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0013_videoproject_heygen_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='style_id',
            field=models.CharField(blank=True, default='f9b6c9115a6f4be99abec4ae0b09657b', max_length=255),
        ),
    ]
