# Generated by Django 5.2.13 on 2026-04-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogen', '0014_videoproject_style_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='is_counted',
            field=models.BooleanField(default=False, help_text='True once the subscription video counter has been incremented for this project.'),
        ),
    ]
